Locale supported as timezone
Readme-Workflows/recent-activity pull request #54
Opened 2021-05-22 12:22 UTC by abhijoshi2k

## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [x] **Major Change**  
  This Pull request will break existing configuration.
- [x] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Timezone support extended. It can now accept locale string as "continent/city"
f.e. GMT+0530 or Asia/Kolkata
Formats for all timezones can be viewed here : https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

🔴🔴 Breaking Change 🔴🔴
`TIMEZONE_OFFSET` input has now changed to `TIMEZONE`

Closes #49 

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

2021-05-22 12:24 UTC, abhijoshi2k commented
@Andre601 We'll be good to resolve #49 after you update readme and changelog.

2021-05-22 15:30 UTC, PuneetGopinath commented
I test the branch in https://github.com/PuneetGopinath/activity-test nowm

2021-05-22 15:36 UTC, PuneetGopinath commented
@abhijoshi2k See those results in https://github.com/PuneetGopinath/activity-test/actions/runs/866856864
They passed

2021-05-22 15:37 UTC, PuneetGopinath commented
@abhijoshi2k Is there something you want to still commit in the timezone-fix branch?

2021-05-22 15:39 UTC, abhijoshi2k commented
> @abhijoshi2k Is there something you want to still commit in the timezone-fix branch?

Changelog is still left

2021-05-22 15:45 UTC, abhijoshi2k commented
@PuneetGopinath let us stop all the work on #53 till this pr is merged and all conflicts are resolved.

2021-05-22 15:51 UTC, PuneetGopinath commented
@abhijoshi2k Why do we have to release minor version can't we release a new major version, v1.3.0 of our release has not followed semantic version already, can I update the Changelog and the draft release?

2021-05-22 15:52 UTC, abhijoshi2k commented
> @abhijoshi2k Why do we have to release minor version can't we release a new major version, v1.3.0 of our release has not followed semantic version already, can I update the Changelog and the draft release?

Yes, we can go for v2.0.0 in next release

2021-05-22 15:54 UTC, Andre601 commented
That's not how semantic versioning works imo

2021-05-22 15:55 UTC, PuneetGopinath commented
> That's not how semantic versioning works imo.
> 1.4.0 is perfectly fine...

How?

2021-05-22 15:56 UTC, PuneetGopinath commented
Semver says to use a new major version when there is a breaking change.

2021-05-22 15:57 UTC, abhijoshi2k commented
> That's not how semantic versioning works imo.
> 1.4.0 is perfectly fine...

Let's release new version after #53 is merged.
It has totally new structure and major breaking changes. I think it'll be worth v2.0

2021-05-22 15:59 UTC, Andre601 approved these changes

2021-05-22 16:01 UTC, Andre601 requested changes
I dislike that we delete the old changelog.
This goes completely against the purpose of a Change**LOG**

2021-05-22 16:02 UTC, PuneetGopinath commented on functions/appendDate.js
> +      process.env.TZ = TIMEZONE;
@abhijoshi2k Sorry, I don't know from where the `process.env.TZ` came, is the process variable built-in in node.js

2021-05-22 16:03 UTC, abhijoshi2k commented
> I dislike that we delete the old changelog.
> This goes completely against the purpose of a Change**LOG**

@PuneetGopinath I agree with @Andre601 Let's not delete the old changelog.

2021-05-22 16:03 UTC, abhijoshi2k commented on functions/appendDate.js
> +      process.env.TZ = TIMEZONE;
Yes it's built in

2021-05-22 16:04 UTC, PuneetGopinath commented
> I dislike that we delete the old changelog.
> This goes completely against the purpose of a Change**LOG**

No, we should reset it when a new version is released, that's why in the old format, I added the older changelogs section you removed it!!

2021-05-22 16:07 UTC, abhijoshi2k commented
@PuneetGopinath @Andre601  can we keep changelogs of old version in separate folder then?

2021-05-22 16:08 UTC, PuneetGopinath commented
This doesn't

> @PuneetGopinath @Andre601 can we keep changelogs of old version in separate folder then?

Yes, we can keep them, anyway they are available in the v1.3.0 tag

2021-05-22 16:10 UTC, Andre601 commented
> @PuneetGopinath @Andre601 can we keep changelogs of old version in separate folder then?

At least do that and link to it in the current change log...
But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.

2021-05-22 16:11 UTC, PuneetGopinath commented
> At least do that and link to it in the current change log...
> But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.

Don't become angery 😆

2021-05-22 16:15 UTC, PuneetGopinath commented
Can I merge.

2021-05-22 16:15 UTC, abhijoshi2k commented
> At least do that and link to it in the current change log...
> But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.

There's no need to get angry @Andre601 .
Let's work as a team. I don't think getting angry and exiting is a solution here. Mistakes do happen. Let's be considerate. 😊

2021-05-22 16:17 UTC, abhijoshi2k commented
> Can I merge.

Let's not hurry. Wait for @Andre601 to respond.

2021-05-22 16:18 UTC, PuneetGopinath commented
@Andre601 Only one chance went, there are 99+ more chances left!! Never become angry!

2021-05-22 16:18 UTC, Andre601 commented
> > At least do that and link to it in the current change log...
> > But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.
> 
> Don't become angery 😆

I am.
I work more than enough with projects who use semantic versioning and now you come here and essentially piss on this.
I never in my life saw any project that jumps to a new major version for some feature changes. So far I only saw actual major changes happening on entire recodes of the code. Everything else at most caused a minor change.

The actual, true semantic versioning is `major.minor.patch_build` where major is for recodes/extreme code changes, minor for changes without backwards compatibility, patch for changes with backwards compatibility and build for bug fixes and similar.

See for example [JDA](https://github.com/DV8FromTheWorld/JDA)

It's just annoying that I'm here for README and CHANGELOG changes, yet you two take this over now and I get the back seat and reviewer role...

2021-05-22 16:18 UTC, PuneetGopinath commented
I hurried because, am going to sleep

2021-05-22 16:19 UTC, Andre601 commented
Just make a backup of the old (v1) changelog now... Maybe in a `.github/archives` folder and named `CHANGELOG_v1.md`
That's all I ask for now.

2021-05-22 16:20 UTC, abhijoshi2k commented
> I hurried because, am going to sleep

I shall merge it after we clear everything with @Andre601 . I don't want to hurt a team member here. I shall also resolve all the conflicts. You can sleep.

2021-05-22 16:21 UTC, PuneetGopinath commented
> Just make a backup of the old (v1) changelog now... Maybe in a `.github/archives` folder and named `CHANGELOG_v1.md`
> That's all I ask for now.

@abhijoshi2k You can get the old change log from the old changelogs section, then copy the raw content and create a new file.

2021-05-22 16:22 UTC, abhijoshi2k commented
> > > At least do that and link to it in the current change log...
> > > But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.
> > 
> > Don't become angery 😆
> 
> I am.
> I work more than enough with projects who use semantic versioning and now you come here and essentially piss on this.
> I never in my life saw any project that jumps to a new major version for some feature changes. So far I only saw actual major changes happening on entire recodes of the code. Everything else at most caused a minor change.
> 
> The actual, true semantic versioning is `major.minor.patch_build` where major is for recodes/extreme code changes, minor for changes without backwards compatibility, patch for changes with backwards compatibility and build for bug fixes and similar.
> 
> See for example [JDA](https://github.com/DV8FromTheWorld/JDA)
> 
> It's just annoying that I'm here for README and CHANGELOG changes, yet you two take this over now and I get the back seat and reviewer role...

@PuneetGopinath let's make sure this doesn't happen anymore.
@Andre601 I'm sorry that this happened.
Let's put it in past and start fresh.
I hope you understand.

2021-05-22 16:23 UTC, PuneetGopinath commented
@abhijoshi2k We have breaking changes and that should release a new major version

2021-05-22 16:52 UTC, Andre601 commented
I merged a `.github/changelogs/CHANGELOG_v1.md` file into this branch now.

2021-05-22 16:52 UTC, Andre601 approved these changes

2021-05-22 16:55 UTC, merged

2021-05-22 17:54 UTC, StevenJDH commented
> 
> 
> > > At least do that and link to it in the current change log...
> > > But whatever. I don't have anything to do here anymore, since you two took over my only purpose here. So do wtf you want Idc anymore.
> > 
> > 
> > Don't become angery 😆
> 
> I am.
> I work more than enough with projects who use semantic versioning and now you come here and essentially piss on this.
> I never in my life saw any project that jumps to a new major version for some feature changes. So far I only saw actual major changes happening on entire recodes of the code. Everything else at most caused a minor change.
> 
> The actual, true semantic versioning is `major.minor.patch_build` where major is for recodes/extreme code changes, minor for changes without backwards compatibility, patch for changes with backwards compatibility and build for bug fixes and similar.
> 
> See for example [JDA](https://github.com/DV8FromTheWorld/JDA)
> 
> It's just annoying that I'm here for README and CHANGELOG changes, yet you two take this over now and I get the back seat and reviewer role...

Hello @Andre601 and all, I just wanted to provide my two cents since my original ticket spurred this discussion and I don't want to see people upset on great working being done already. Debating can be a good thing and even healthy as long as no one takes it personal, and with versioning, there are always a lot of opinions. With that said, I will just share this, https://semver.org/. These are very clear guidelines, and with regards to Minor version, it says `MINOR version when you add functionality in a backwards compatible manner.` The key here is minor is not for breaking changes, but backwards compatible ones such as new features, or perhaps supporting new breaking changes of existing features while still supporting the old way marked as deprecated.

Keeping in mind the above, I think, at least in part, that some of the confusion is coming from releasing maybe too few breaking changes as a new version. For example, 1 breaking change causing the major version to update each time, which feels wrong as opposed to maybe 10. The discussion above seems to hover around both of these concepts. I won't say what I think is best, but I did just want to share some info in the hopes it helps work things out easier.

Thanks again everyone for your time and involvement in this.

2021-05-22 18:10 UTC, abhijoshi2k commented
Hello @StevenJDH ,
Thanks for the valuable information provided by you. We will surely go through it and take proper steps.
I hope that issue you faced regarding DST has been resolved.
Also, I wish to let you know that if you are using the `main` branch for your workflow, please note that the file structure is going to be changed after #53 will be merged. Surely, the readme will be updated accordingly.
We will make sure we mention you in here to remind whenever #53 is merged and new version is released.

Thank you.

2021-05-22 18:26 UTC, StevenJDH commented
@abhijoshi2k yes, things look good. And yes, I've decided to switch from main to a version number after reconsidering my approach here. Thanks again 🙏🏽

2021-05-23 09:54 UTC, abhijoshi2k commented
@StevenJDH The feature you requested is now released with v2.0.0
You can now use it with separate config file. Documentation is available [here](https://github.com/Readme-Workflows/recent-activity/wiki)

2021-05-23 11:44 UTC, StevenJDH commented
@abhijoshi2k perfect, I will upgrade today, thanks!