Add custom committer
Readme-Workflows/recent-activity pull request #63
Opened 2021-05-26 17:53 UTC by Lorenzo0111

## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Added an option to edit committer name and email.

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

2021-05-26 19:08 UTC, Andre601 commented
I for my part can't see the real benefit here. But I let the other maintainers give their feedback

2021-05-27 00:29 UTC, PuneetGopinath commented
Hi @Lorenzo0111!
Thanks for this PR.
But currently we this action is in an idle state.
That we announced in our discord server:
```
🥁 Recent Activity action is idle for 2 weeks 🥁

Hello everyone!
We are sad 😢 to inform you that Recent Activity action is idle 😴 for 2 more weeks.
As we also want to give rest to our maintainers and one of our maintainer (Abishek Joshi), his vivas and sems are gonna start from tomorrow (some exams).
We worked continuously for many days to bring new features and fix bugs.
You can still submit feature requests and bug reports, but we will not be able to finish them as our functionality maintainer (Abishek Joshi) is not available, I (Puneet Gopinath) sometimes can fix bugs and fulfill feature requests, but without approval of Abishek we can't merge PRs, etc.
So we mention that Recent Activity action is idle for 2 more weeks.
That means it is idle till 31 May 2021.
```
Please wait for Abishek 🙏.

2021-05-27 00:32 UTC, PuneetGopinath commented
Andre, just update the Changelog.

2021-05-27 00:37 UTC, PuneetGopinath requested changes

2021-05-27 00:37 UTC, PuneetGopinath commented on src/functions/commitFile.js
> +  await exec("git", ["config", "--global", "user.name", commitName]);
Where did you define `commitEmail` and `commitName`, aren't they `commit_email` and `commit_name`

2021-05-27 02:44 UTC, PuneetGopinath commented
Hi @Lorenzo0111.
Can you give permission for maintaners to edit.
Docs: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
After I merge branch main, can you update the docs in `docs/Configuration.md`

2021-05-27 07:51 UTC, abhijoshi2k requested changes
Please change the incorrect variable names in `src/functions/commitFile.js` and merge latest commits from `main` branch.
After that, update the `docs/Configuration.md`

2021-05-27 13:55 UTC, Lorenzo0111 commented
> 
> 
> Hi @Lorenzo0111.
> Can you give permission for maintaners to edit.
> Docs: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> After I merge branch main, can you update the docs in `docs/Configuration.md`

Done
![immagine](https://user-images.githubusercontent.com/69311874/119838767-f1f36780-bf03-11eb-9d6e-c41873173a9d.png)

2021-05-27 14:08 UTC, PuneetGopinath commented
Or else you can follow this help: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/merging-an-upstream-repository-into-your-fork

2021-05-27 15:03 UTC, PuneetGopinath commented
@Lorenzo0111 Can you resolve the [requested changes](https://github.com/Readme-Workflows/recent-activity/pull/63#pullrequestreview-669647855)?

2021-05-27 15:11 UTC, Lorenzo0111 commented
> 
> 
> @Lorenzo0111 Can you resolve the [requested changes](https://github.com/Readme-Workflows/recent-activity/pull/63#pullrequestreview-669647855)?

done

2021-05-27 15:23 UTC, PuneetGopinath requested changes

2021-05-27 15:23 UTC, PuneetGopinath commented on dist/index.js
> +  await exec("git", ["config", "--global", "user.name", commitName]);
Here also, the same fix is required

2021-05-27 15:24 UTC, PuneetGopinath requested changes

2021-05-27 15:24 UTC, PuneetGopinath commented on dist/index.js
> +    commitEmail,
This line also

2021-05-27 15:29 UTC, Andre601 approved these changes
You shouldn't request my review here, since I don't have the proper knowledge of this coding language to give proper feedback

2021-05-27 15:31 UTC, Lorenzo0111 commented
> 
> 
> You shouldn't request my review here, since I don't have the proper knowledge of this coding language to give proper feedback

I didn't requested it. I think it is automatic

2021-05-27 15:34 UTC, Andre601 commented
> > You shouldn't request my review here, since I don't have the proper knowledge of this coding language to give proper feedback
> 
> I didn't requested it. I think it is automatic

True. Just saw it.

2021-05-27 15:37 UTC, PuneetGopinath commented
> You shouldn't request my review here, since I don't have the proper knowledge of this coding language to give proper feedback

He didn't, you are a CODEOWNER

2021-05-27 15:37 UTC, PuneetGopinath commented
> > > You shouldn't request my review here, since I don't have the proper knowledge of this coding language to give proper feedback
> > 
> > 
> > I didn't requested it. I think it is automatic
> 
> True. Just saw it.

You have to review it, as their as changes in docs

2021-05-27 15:38 UTC, PuneetGopinath approved these changes

2021-05-27 16:12 UTC, abhijoshi2k approved these changes
It's working properly!

2021-05-27 16:16 UTC, merged