Create Examples.md
Readme-Workflows/recent-activity pull request #64
Opened 2021-05-27 18:21 UTC by Andre601

## Checks

I have...

- [ ] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [ ] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Replace this line with a description about the changes you have made in this PR (Correcting typos, adding new features, etc.)

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

2021-05-27 19:27 UTC, abhijoshi2k approved these changes

2021-05-28 00:24 UTC, PuneetGopinath commented
Changelog?

2021-05-28 00:31 UTC, PuneetGopinath requested changes
Please update the Changelog

2021-05-28 00:38 UTC, PuneetGopinath requested changes

2021-05-28 00:38 UTC, PuneetGopinath commented on docs/README.md
> +# Recent Activity Wiki
```suggestion
# Welcome Recent Activity's Wiki
```

2021-05-28 00:38 UTC, PuneetGopinath commented on docs/Home.md
> +- [[Examples]] (Outdated. Use the Configuration page instead!)
```suggestion
- [[Examples]] (Outdated. v1.3.0 and older)
```

2021-05-28 09:27 UTC, Andre601 commented on docs/README.md
> +# Recent Activity Wiki
Sounds a bit bad imo.

Maybe `Welcome to the Wiki of Recent Activity`?

2021-05-28 09:37 UTC, PuneetGopinath commented on docs/README.md
> +# Recent Activity Wiki
I have updated the suggestion

2021-05-28 09:38 UTC, PuneetGopinath commented
> Please update the Changelog

@Andre601

2021-05-28 09:43 UTC, Andre601 commented
> > Please update the Changelog
> 
> @Andre601

Done 👍

2021-05-28 09:46 UTC, PuneetGopinath commented on docs/README.md
> +# Recent Activity Wiki
@Andre601

2021-05-28 09:48 UTC, PuneetGopinath commented
> > > Please update the Changelog
> > 
> > 
> > @Andre601
> 
> Done 👍

Can you also add that we added `docs` folder in #64 in Changelog, I think it will be useful, what's your opinion @abhijoshi2k?

2021-05-28 10:06 UTC, PuneetGopinath approved these changes

2021-05-28 10:06 UTC, merged