Collect data from workflows
Readme-Workflows/recent-activity pull request #67
Opened 2021-05-29 18:51 UTC by abhijoshi2k

## Checks

I have...

- [ ] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Collection of data for analysis purpose. Data collected: `username`, `commit_name`, `commit_email`, time of last workflow run, number of successful/failed runs.
Collected data is refreshed after maximum period of 7 days. Complete data is discarded if workflow is not used for 7 days.

Closes #

[contributing]: https://github.com/Readme-Workflows/recent-activity/blob/main/.github/CONTRIBUTING.md

2021-05-29 19:04 UTC, abhijoshi2k commented
@Andre601  Can you put a declaration at appropriate place saying user data will be collected from version v2.0.1 onwards.
Also update the changelog whenever possible. I'll keep this PR on `Status: In progress` label till you merge the docs changes on this branch.
Information about how data is collected is provided in description of PR.
Thanks.

2021-05-29 19:13 UTC, Andre601 commented
> @Andre601 Can you put a declaration at appropriate place saying user data will be collected from version v2.0.1 onwards.
> Also update the changelog whenever possible. I'll keep this PR on `Status: In progress` label till you merge the docs changes on this branch.
> Information about how data is collected is provided in description of PR.
> Thanks.

Is it now 2.0.1 or 2.1.0?
The release draft mentions 2.1.0 which confuses me.

2021-05-29 19:16 UTC, abhijoshi2k commented
> Is it now 2.0.1 or 2.1.0?
> The release draft mentions 2.1.0 which confuses me.

I'm so sorry I didn't check the release draft. I'm okay with `v2.1.0` too 👍🏻.

2021-05-29 19:25 UTC, abhijoshi2k commented on README.md
> +By using this Action will you agree to allowing the aformentioned data to be collected.
```suggestion
By using this Action, you are agreeing to allow the aformentioned data to be collected.
```
Imo, this would be better statement.

2021-05-30 00:33 UTC, PuneetGopinath requested changes

2021-05-30 00:33 UTC, PuneetGopinath commented on README.md
> +By using this Action, you are agreeing to allow the aformentioned data to be collected.
```suggestion
By using this Action, you are agreeing to allow the aforementioned data to be collected.
```
Just a typo is there

2021-05-30 00:33 UTC, PuneetGopinath commented on src/functions/apiRequest.js
> +    url = "https://readme-workflows.herokuapp.com/usage/recent-activity";
@abhijoshi2k Will you show this URL publicly?

2021-05-30 00:33 UTC, PuneetGopinath commented on src/functions/apiRequest.js
> +    url = "https://readme-workflows.herokuapp.com/usage/recent-activity";
Because they can also run it using GitHub actions

2021-05-30 04:53 UTC, abhijoshi2k commented on src/functions/apiRequest.js
> +    url = "https://readme-workflows.herokuapp.com/usage/recent-activity";
There would be no point of that though. I'll see what I can do. Don't merge this yet.

2021-05-30 09:37 UTC, PuneetGopinath approved these changes

2021-05-30 09:37 UTC, PuneetGopinath commented
@Andre601 Plz review

2021-05-30 09:38 UTC, merged

2021-05-30 09:39 UTC, Andre601 approved these changes