Add amount keyword
Readme-Workflows/recent-activity pull request #90
Opened 2021-08-02 07:39 UTC by abhijoshi2k

## Checks

I have...

- [x] read and understood the [Contributing Guidelines][contributing]
- [ ] Updated any necessary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Combine multiple `changes_requested` events of PR review event into single line

Closes #88 

[contributing]: https://github.com/Readme-Workflows/.github/blob/main/.github/CONTRIBUTING.md

2021-08-02 08:11 UTC, PuneetGopinath approved these changes
I can't understand much

2021-08-02 14:12 UTC, Andre601 requested changes

2021-08-02 14:12 UTC, Andre601 commented on dist/index.js
> +  changes_requested: "🔴 Requested {AMOUNT} change(s) in {ID} in {REPO}",
I feel like this sounds better
```suggestion
  changes_requested: "🔴 Requested {AMOUNT} change(s) for {ID} in {REPO}",
```

2021-08-02 14:12 UTC, Andre601 commented on src/config.js
> +  changes_requested: "🔴 Requested {AMOUNT} change(s) in {ID} in {REPO}",
I feel like this sounds better
```suggestion
  changes_requested: "🔴 Requested {AMOUNT} change(s) for {ID} in {REPO}",
```

2021-08-02 17:02 UTC, abhijoshi2k commented on dist/index.js
> +  changes_requested: "🔴 Requested {AMOUNT} change(s) in {ID} in {REPO}",
Cool

2021-08-02 18:07 UTC, abhijoshi2k commented
The workflow is working as expected. Please review and merge if there are no more changes required.

2021-08-03 10:42 UTC, Andre601 approved these changes
I really don't know why you ask me for reviews here. I'm not a JS guy...

2021-08-03 18:02 UTC, merged